# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /community
# 应用名称
spring:
  application:
    name: Community
  datasource:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
    # 数据源名称
    name: defaultDataSource
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/db_community?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: wzk
  # THYMELEAF (ThymeleafAutoConfiguration)
  # 关闭模板缓存（默认值： true ）
  thymeleaf:
    cache: false
  # 邮箱
  mail:
    host: smtp.qq.com
    protocol: smtp
    port: 465
    username: 985319769@qq.com
    password: eashfcnatlawbbfd
    properties.smtp.auth: true
    properties.smtp.timeout: 2500
    properties.mail.smtp.ssl.enable: true
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#指定Mybatis的实体目录
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.serein.community.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    use-generated-keys: true

logging:
  level:
    root: info
    com.serein.community: debug
  file:
    name: log/community-dev.log

# community
community:
  path:
    domain: http://localhost:8080
    upload: E:/下载/upload

#spring.thymeleaf.cache=true
## 检查模板是否存在，然后再呈现
#spring.thymeleaf.check-template=true
## 检查模板位置是否正确（默认值 :true ）
#spring.thymeleaf.check-template-location=true
##Content-Type 的值（默认值： text/html ）
#spring.thymeleaf.content-type=text/html
## 开启 MVC Thymeleaf 视图解析（默认值： true ）
#spring.thymeleaf.enabled=true
## 模板编码
#spring.thymeleaf.encoding=UTF-8
## 要被排除在解析之外的视图名称列表，⽤逗号分隔
#spring.thymeleaf.excluded-view-names=
## 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
#spring.thymeleaf.mode=HTML5
## 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
#spring.thymeleaf.prefix=classpath:/templates/
## 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
#spring.thymeleaf.suffix=.html

